template: vote-service
deployments:
  development:
    target: dev
    clusters: 0
    values:
      image: ghcr.io/cse-labs/go-vote:latest
      port: 8080
      title: "What's for dinner?"
      key1: Steak
      key2: Chicken
