template: vote-service
deployments:
  development:
    target: dev
    clusters: 1
    values:
      image: ghcr.io/cse-labs/go-vote:latest
      port: 8080
      title: "Where is your next vacation?"
      key1: Beach
      key2: Mountains
